### ISSUE TITLE
[Help Required] Missing Subscriptions

### ISSUE THREAD

**Issue by planet4** [yesoreyeram/grafana-azure-datasource#16]
I will open another issue here and you can close it if there is something I have done wrong. I tried to add the datasource again now and I know the access is correct. I have four subscriptions but it will only find the first one.

![subscriptions](https://user-images.githubusercontent.com/22392924/89292528-c9406f80-d65c-11ea-8661-d20c04ad1b1f.PNG)

**Comment by yesoreyeram** [comment]
Can you create new data source instance and see if the same amount of subscriptions? Just wanted to confirm if the issue occurs only for the existing data source alone.

**Comment by planet4** [comment]
Well, I added another one but still get only one. The problem might be in Azure as well but it is hard to tell?

**Comment by yesoreyeram** [comment]
Strange.i have implemented this for few tenants. Never seen his behavior.

Well, to debug i suggest following steps.

Method 1 :  Use grafana native azure monitor plugin with same credentials and see how many subscriptions retrieved.

Method 2 : use az login cli command and login with the SPN and see how many subscription retrieved.

If any of the methods returned more than one subscription, plugin needs to be fixed. Otherwise your SPN missing permissions

**Comment by planet4** [comment]
You are correct. Sorry for that. I did try another app and now it works.

**Comment by yesoreyeram** [comment]
Ah. Can this issue closed? or you want me to do further investigation?
